services:
  - type: web
    name: namma-svit-erp
    env: node
    plan: starter
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: namma-svit-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: AUTH_SECRET
        generateValue: true
    healthCheckPath: /

databases:
  - name: namma-svit-db
    plan: starter

